// <auto-generated />
using CrowdSpark.Entitites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CrowdSpark.Entitites.Migrations
{
    [DbContext(typeof(CrowdSparkContext))]
    [Migration("20171218174501_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrowdSpark.Entitites.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoryId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CreatorId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("LocationId");

                    b.Property<int?>("SkillId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SkillId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.ProjectSkill", b =>
                {
                    b.Property<int>("SkillId");

                    b.Property<int>("ProjectId");

                    b.HasKey("SkillId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectSkill");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.Spark", b =>
                {
                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Status");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Sparks");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AzureUId")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int?>("LocationId");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("SkillId");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SkillId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.UserSkill", b =>
                {
                    b.Property<int>("SkillId");

                    b.Property<int>("UserId");

                    b.HasKey("SkillId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkill");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.Project", b =>
                {
                    b.HasOne("CrowdSpark.Entitites.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("CrowdSpark.Entitites.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrowdSpark.Entitites.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("CrowdSpark.Entitites.Skill")
                        .WithMany("Projects")
                        .HasForeignKey("SkillId");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.ProjectSkill", b =>
                {
                    b.HasOne("CrowdSpark.Entitites.Project", "Project")
                        .WithMany("Skills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrowdSpark.Entitites.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CrowdSpark.Entitites.Spark", b =>
                {
                    b.HasOne("CrowdSpark.Entitites.Project", "Project")
                        .WithMany("Sparks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrowdSpark.Entitites.User", "User")
                        .WithMany("Sparks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CrowdSpark.Entitites.User", b =>
                {
                    b.HasOne("CrowdSpark.Entitites.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("CrowdSpark.Entitites.Skill")
                        .WithMany("Users")
                        .HasForeignKey("SkillId");
                });

            modelBuilder.Entity("CrowdSpark.Entitites.UserSkill", b =>
                {
                    b.HasOne("CrowdSpark.Entitites.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrowdSpark.Entitites.User", "User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
